let CHAMPIONBYID = Object.freeze({
    '0': 'Aatrox',
    '1': 'Ahri',
    '2': 'Akali',
    '3': 'Alistar',
    '4': 'Amumu',
    '5': 'Anivia',
    '6': 'Annie',
    '7': 'Aphelios',
    '8': 'Ashe',
    '9': 'Aurelion Sol',
    '10': 'Azir',
    '11': 'Bard',
    '12': 'Blitzcrank',
    '13': 'Brand',
    '14': 'Braum',
    '15': 'Caitlyn',
    '16': 'Camille',
    '17': 'Cassiopeia',
    '18': "Cho'Gath",
    '19': 'Corki',
    '20': 'Darius',
    '21': 'Aatrox',
    '22': 'Diana', //BEST CHAMPION <3
    '23': 'Draven',
    '24': 'Dr.Mundo',
    '25': 'Ekko',
    '26': 'Elise',
    '27': 'Evelynn',
    '28': 'Ezreal',
    '29': 'Fiddlesticks',
    '30': 'Fiora',
    '31': 'Fizz',
    '32': 'Galio',
    '33': 'Gangplank',
    '34': 'Garen',
    '35': 'Gnar',
    '36': 'Gragas',
    '37': 'Graves',
    '38': 'Hecarim',
    '39': 'Heimerdinger',
    '40': 'Illaoi',
    '41': 'Irelia',
    '42': 'Ivern',
    '43': 'Janna',
    '44': 'Jarvan IV', // A verifier l'ecriture de l'api
    '45': 'Jax',
    '46': 'Jayce',
    '47': 'Jhin',
    '48': 'Jinx',
    '49': "Kai'Sa", // A verifier l'ecriture de l'api
    '50': 'Kalista',
    '51': 'Karma',
    '52': 'Karthus',
    '53': 'Katarina',
    '54': 'Kayle',
    '55': 'Kayn',
    '56': 'Kennen',
    '57': "Kha'Zix", // A verifier
    '58': 'Kindred',
    '59': 'Kled',
    '60': "Kog'Maw", // A verifier
    '61': 'LeBlanc', // A verifier
    '62': 'Lee Sin',
    '63': 'Leona',
    '64': 'Lisssandra',
    '65': 'Lucian',
    '66': 'Lulu',
    '67': 'Lux',
    '68': 'Maitre Yi',
    '69': 'Malphite',
    '70': 'Malzahar',
    '71': 'Maokai',
    '72': 'Miss Fortune', // A verifier
    '73': 'Mordekaiser',
    '74': 'Morgana',
    '75': 'Nami',
    '76': 'Nasus',
    '77': 'Nautilus',
    '78': 'Neeko',
    '79': 'Nidalee',
    '80': 'Nocture',
    '81': 'Nunu et Willump', // A verifier
    '82': 'Olaf',
    '83': 'Orianna',
    '84': 'Ornn',
    '85': 'Pantheon',
    '86': 'Poppy',
    '87': 'Pyke',
    '88': 'Qiyana',
    '89': 'Aatrox',
    '90': 'Quinn',
    '91': 'Rakan',
    '92': 'Ramus',
    '93': "Rek'Sai", // A verifier
    '94': 'Renekton',
    '95': 'Rengar',
    '96': 'Riven',
    '97': 'Rumble',
    '98': 'Ryze',
    '99': 'Sejuani',
    '100': 'Senna',
    '101': 'Sett',
    '102': 'Shaco',
    '103': 'Shen',
    '104': 'Shyvana',
    '105': 'Singed',
    '106': 'Sion',
    '107': 'Sivir',
    '108': 'Skarner',
    '109': 'Sona',
    '110': 'Soraka',
    '111': 'Swain',
    '112': 'Sylas',
    '113': 'Syndra',
    '114': 'Tahm Kench', // A verifier
    '115': 'Taliyah',
    '116': 'Talon',
    '117': 'Taric',
    '118': 'Teemo',
    '119': 'Tresh',
    '120': 'Tristana',
    '121': 'Trundle',
    '122': 'Tryndamere',
    '123': 'Twisted Fate', // A verifier
    '124': 'Twitch',
    '125': 'Udyr',
    '126': 'Urgot',
    '127': 'Varus',
    '128': 'Vayne',
    '129': 'Veigar',
    '130': "Vel'Koz", // A verifier
    '131': 'Vi',
    '132': 'Viktor',
    '133': 'Vladimir',
    '134': 'Volibear',
    '135': 'Warwick',
    '136': 'Wukong',
    '137': 'Xayah',
    '138': 'Xerath',
    '139': 'Xin Zhao', // A verifier
    '140': 'Yasuo',
    '141': 'Yorick',
    '142': 'Yuumi',
    '143': 'Zac',
    '144': 'Zed',
    '145': 'Ziggs',
    '146': 'Zilean',
    '147': 'Zoe',
    '148': 'Zira',
})